### ISSUE TITLE
SitumSDK/SitumSDK.h file not found

### ISSUE THREAD

**Issue by farhanlatheef** [situmtech/situm-ios-code-samples#2]
I clone this project. ran pod install, all libraries including situmSDK is linked in "build phase". but when i try to build i get "SitumSDK/SitumSDK.h file not found" error. I remove and re add the situmSDK without any success

**Comment by CrisBarreiro** [comment]
Closed as several versions have been released since the issue was opened. If the problem persists, please open a new issue or drop an email to support@situm.es
